name: Lint Dockerfile

on: [push, pull_request]

jobs:
  lint-docker:
    name: Hadolint Dockerfile Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
